"""Add is_cash and required_gender to Item model

Revision ID: 5f278f0f2e4f
Revises: 
Create Date: 2023-03-17 23:59:30.255999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f278f0f2e4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cash', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('required_gender', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('required_gender')
        batch_op.drop_column('is_cash')

    # ### end Alembic commands ###
