"""empty message

Revision ID: 0531d156efad
Revises: c6cbf4459baf
Create Date: 2023-03-16 20:30:02.107505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0531d156efad'
down_revision = 'c6cbf4459baf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('inscription')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inscription', sa.TEXT(), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
