"""empty message

Revision ID: 105828ab5460
Revises: 77df6a7b88c9
Create Date: 2023-03-19 22:12:22.389372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105828ab5460'
down_revision = '77df6a7b88c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ShowRoom')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ShowRoom',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('show_room')
    # ### end Alembic commands ###
