"""empty message

Revision ID: 123f29cf69a4
Revises: 6ac2d0043c4a
Create Date: 2023-03-18 02:52:13.048010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123f29cf69a4'
down_revision = '6ac2d0043c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key('fk_inventory_user_id', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_inventory_item_id', 'item', ['item_id'], ['id'])
        batch_op.drop_column('item_name')
        batch_op.drop_column('username')
        batch_op.drop_column('enhance')
        batch_op.drop_column('grade')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('point')
        batch_op.drop_column('money')
        batch_op.drop_column('password')
        batch_op.drop_column('level')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('level', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('money', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('point', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('enhance', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('item_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_inventory_item_id', type_='foreignkey')
        batch_op.drop_constraint('fk_inventory_user_id', type_='foreignkey')
        batch_op.drop_column('name')
        batch_op.drop_column('item_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
