"""empty message

Revision ID: 145a598be6b1
Revises: 0531d156efad
Create Date: 2023-03-16 20:40:39.706837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145a598be6b1'
down_revision = '0531d156efad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
