"""empty message

Revision ID: 61a84eced346
Revises: c7cb3c20f697
Create Date: 2023-03-18 05:47:48.863409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a84eced346'
down_revision = 'c7cb3c20f697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('inven_item_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='fk_inventory_item_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_inventory_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['user_name'])
        batch_op.drop_column('name')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['item_name'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('item_name')

    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_name')

    op.drop_table('inventory')
    # ### end Alembic commands ###
