"""empty message

Revision ID: 6ac2d0043c4a
Revises: 5a65baf1f1e3
Create Date: 2023-03-18 02:46:42.957058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac2d0043c4a'
down_revision = '5a65baf1f1e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hair', sa.String(length=100), nullable=True),
    sa.Column('boots', sa.String(length=100), nullable=True),
    sa.Column('shirts', sa.String(length=100), nullable=True),
    sa.Column('pants', sa.String(length=100), nullable=True),
    sa.Column('weapon', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('wallet', sa.Integer(), nullable=False),
    sa.Column('eval_point', sa.Integer(), nullable=False),
    sa.Column('money', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('exp', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('enhancement', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('market')
    op.drop_table('inven')
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'item', ['item_id'], ['id'])
        batch_op.drop_column('grade')
        batch_op.drop_column('item_name')
        batch_op.drop_column('username')
        batch_op.drop_column('enhance')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('level')
        batch_op.drop_column('username')
        batch_op.drop_column('money')
        batch_op.drop_column('point')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('point', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('money', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('level', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enhance', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('item_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('grade', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('name')
        batch_op.drop_column('item_id')
        batch_op.drop_column('user_id')

    op.create_table('inven',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('enhance', sa.INTEGER(), nullable=True),
    sa.Column('grade', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('item_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('grade', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_name')
    )
    op.drop_table('item')
    op.drop_table('info')
    op.drop_table('equipment')
    # ### end Alembic commands ###
