"""empty message

Revision ID: 77df6a7b88c9
Revises: aea063b9c86c
Create Date: 2023-03-19 22:11:46.706533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77df6a7b88c9'
down_revision = 'aea063b9c86c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ShowRoom')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ShowRoom',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Inventory')
    # ### end Alembic commands ###
