"""empty message

Revision ID: 93ca4398b250
Revises: 77e60ac2a6d7
Create Date: 2023-03-16 20:13:37.459311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ca4398b250'
down_revision = '77e60ac2a6d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('enhance', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('inscription', sa.Text(), nullable=True))
        batch_op.drop_column('enhance')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('purchased_item_list')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased_item_list', sa.BLOB(), nullable=True))

    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enhance', sa.INTEGER(), nullable=True))
        batch_op.drop_column('inscription')
        batch_op.drop_column('grade')

    op.drop_table('inventory')
    # ### end Alembic commands ###
