"""empty message

Revision ID: 940bd1883bbf
Revises: 1c85d5068061
Create Date: 2023-03-20 06:23:35.784091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940bd1883bbf'
down_revision = '1c85d5068061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ItemName', sa.String(length=100), nullable=True),
    sa.Column('Category', sa.Text(), nullable=True),
    sa.Column('SubCategory', sa.Text(), nullable=True),
    sa.Column('Enhancement', sa.Integer(), nullable=False),
    sa.Column('Mounted', sa.Boolean(), nullable=False),
    sa.Column('Icon', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Title')
    )
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(length=20), nullable=False),
    sa.Column('Wallet', sa.Integer(), nullable=False),
    sa.Column('Money', sa.Integer(), nullable=False),
    sa.Column('EvalPoint', sa.Integer(), nullable=False),
    sa.Column('Level', sa.Integer(), nullable=False),
    sa.Column('EXP', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('UserName')
    )
    op.create_table('show_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['inventory.id'], name='fk_ShowRoom'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_room')
    op.drop_table('user_info')
    op.drop_table('subject')
    op.drop_table('inventory')
    # ### end Alembic commands ###
