"""empty message

Revision ID: 980857625e5c
Revises: 
Create Date: 2023-03-16 02:46:29.552324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '980857625e5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
