"""empty message

Revision ID: a09998af7b1e
Revises: e702e707847f
Create Date: 2023-03-16 20:18:24.262859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09998af7b1e'
down_revision = 'e702e707847f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_inventory')
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('enhance',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('inscription', sa.Text(), nullable=True))
        batch_op.drop_column('enhance')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('purchased_item_list')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased_item_list', sa.BLOB(), nullable=True))

    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enhance', sa.INTEGER(), nullable=True))
        batch_op.drop_column('inscription')
        batch_op.drop_column('grade')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('enhance',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_inventory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('enhance', sa.INTEGER(), nullable=True),
    sa.Column('grade', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
