"""empty message

Revision ID: a381bd131a20
Revises: a1dd8b21d092
Create Date: 2023-03-16 10:45:16.603655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a381bd131a20'
down_revision = 'a1dd8b21d092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('itemPossession', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('itemPossession')

    # ### end Alembic commands ###
