"""empty message

Revision ID: aea063b9c86c
Revises: c436ace82f2b
Create Date: 2023-03-19 22:08:47.993567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea063b9c86c'
down_revision = 'c436ace82f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ItemName', sa.String(length=100), nullable=True),
    sa.Column('Category', sa.Text(), nullable=True),
    sa.Column('SubCatrgory', sa.Text(), nullable=True),
    sa.Column('Enhancement', sa.Integer(), nullable=False),
    sa.Column('Mount', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ItemName')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Title')
    )
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(length=20), nullable=False),
    sa.Column('Wallet', sa.Integer(), nullable=False),
    sa.Column('Money', sa.Integer(), nullable=False),
    sa.Column('EvalPoint', sa.Integer(), nullable=False),
    sa.Column('Level', sa.Integer(), nullable=False),
    sa.Column('EXP', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('UserName')
    )
    op.create_table('ShowRoom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ShowRoom')
    op.drop_table('user_info')
    op.drop_table('subject')
    op.drop_table('inventory')
    # ### end Alembic commands ###
