"""empty message

Revision ID: b68a48928e19
Revises: c9a960ef7765
Create Date: 2023-03-16 09:26:56.976921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68a48928e19'
down_revision = 'c9a960ef7765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enhance', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('money', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('money')

    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.drop_column('enhance')

    # ### end Alembic commands ###
