"""empty message

Revision ID: c7cb3c20f697
Revises: 3deb0df0561f
Create Date: 2023-03-18 05:44:32.129284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7cb3c20f697'
down_revision = '3deb0df0561f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['user_name'])
        batch_op.drop_column('name')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('inven_item_name', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['item_name'])
        batch_op.create_foreign_key('inventory_item_id', 'item', ['item_id'], ['id'])
        batch_op.create_foreign_key('inventory_user_id', 'users', ['user_id'], ['id'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('inventory_user_id', type_='foreignkey')
        batch_op.drop_constraint('inventory_item_id', type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('inven_item_name')
        batch_op.drop_column('item_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('item_name')

    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
