"""empty message

Revision ID: d0427ac5041a
Revises: df93ce0cee48
Create Date: 2023-03-20 06:06:28.463064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0427ac5041a'
down_revision = 'df93ce0cee48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_ShowRoom', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'inventory', ['fk_ShowRoom'], ['id'])
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'inventory', ['id'], ['id'])
        batch_op.drop_column('fk_ShowRoom')

    # ### end Alembic commands ###
