"""empty message

Revision ID: d2c9e116954f
Revises: 93ca4398b250
Create Date: 2023-03-16 20:16:04.585205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c9e116954f'
down_revision = '93ca4398b250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_market')
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('inscription', sa.Text(), nullable=True))
        batch_op.drop_column('enhance')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('purchased_item_list')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased_item_list', sa.BLOB(), nullable=True))

    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enhance', sa.INTEGER(), nullable=True))
        batch_op.drop_column('inscription')
        batch_op.drop_column('grade')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('_alembic_tmp_market',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('grade', sa.INTEGER(), nullable=False),
    sa.Column('inscription', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_name')
    )
    # ### end Alembic commands ###
