"""empty message

Revision ID: df93ce0cee48
Revises: e367cf624e51
Create Date: 2023-03-20 05:35:09.157667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df93ce0cee48'
down_revision = 'e367cf624e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SubCategory', sa.Text(), nullable=True))
        batch_op.drop_column('SubCatergory')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SubCatergory', sa.TEXT(), nullable=True))
        batch_op.drop_column('SubCategory')

    # ### end Alembic commands ###
