"""empty message

Revision ID: e367cf624e51
Revises: 2de7490106ae
Create Date: 2023-03-20 05:34:06.723371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e367cf624e51'
down_revision = '2de7490106ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SubCatergory', sa.Text(), nullable=True))
        batch_op.drop_column('SubCatrgory')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SubCatrgory', sa.TEXT(), nullable=True))
        batch_op.drop_column('SubCatergory')

    # ### end Alembic commands ###
