"""empty message

Revision ID: fdeee69c5f57
Revises: 19dc6792b4c0
Create Date: 2023-03-18 05:56:41.582469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdeee69c5f57'
down_revision = '19dc6792b4c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=True),
    sa.Column('enhancement', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hair', sa.String(length=100), nullable=True),
    sa.Column('boots', sa.String(length=100), nullable=True),
    sa.Column('shirts', sa.String(length=100), nullable=True),
    sa.Column('pants', sa.String(length=100), nullable=True),
    sa.Column('weapon', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('wallet', sa.Integer(), nullable=False),
    sa.Column('eval_point', sa.Integer(), nullable=False),
    sa.Column('money', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('exp', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('inven_item_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='fk_inventory_item_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_inventory_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    op.drop_table('info')
    op.drop_table('equipment')
    op.drop_table('users')
    op.drop_table('item')
    # ### end Alembic commands ###
